// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pkg.security;

import org.springframework.beans.factory.annotation.Configurable;
import pkg.security.Assignments;

privileged aspect Assignments_Roo_Configurable {
    
    declare @type: Assignments: @Configurable;
    
}
